-   id: go-fmt
    name: 'go fmt'
    entry: run-go-fmt.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `gofmt`, requires golang"
-   id: go-unit-tests
    name: 'go-unit-tests'
    entry: run-go-unit-tests.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go test`"
-   id: go-test
    name: 'go-test'
    entry: go-test.sh
#     files: '\.go$'
    language: 'script'
    description: "Runs `go build`, requires golang"    
